// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqhDHZJthlEomMz56Aq9MWXkxg_0KKZik',
    appId: '1:1082266719078:web:29802e4f5f609ac3c76ea7',
    messagingSenderId: '1082266719078',
    projectId: 'quickcab-b8b8a',
    authDomain: 'quickcab-b8b8a.firebaseapp.com',
    databaseURL: 'https://quickcab-b8b8a-default-rtdb.firebaseio.com',
    storageBucket: 'quickcab-b8b8a.appspot.com',
    measurementId: 'G-0M0Y46LP1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEv-qKdYWR06KN4bSkIvwHtEKu-4h8mqk',
    appId: '1:1082266719078:android:9aacbcff1c39d4e0c76ea7',
    messagingSenderId: '1082266719078',
    projectId: 'quickcab-b8b8a',
    databaseURL: 'https://quickcab-b8b8a-default-rtdb.firebaseio.com',
    storageBucket: 'quickcab-b8b8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGow4VGDXQiy4oJRYZ7w5s8myP_rJtnhU',
    appId: '1:1082266719078:ios:86c08a302bfc719ac76ea7',
    messagingSenderId: '1082266719078',
    projectId: 'quickcab-b8b8a',
    databaseURL: 'https://quickcab-b8b8a-default-rtdb.firebaseio.com',
    storageBucket: 'quickcab-b8b8a.appspot.com',
    androidClientId: '1082266719078-o8im8a4qmnj47m8mr454i2h5jegkeskm.apps.googleusercontent.com',
    iosClientId: '1082266719078-pslorj2sjkd17fffq157o07fb2n1umro.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGow4VGDXQiy4oJRYZ7w5s8myP_rJtnhU',
    appId: '1:1082266719078:ios:86c08a302bfc719ac76ea7',
    messagingSenderId: '1082266719078',
    projectId: 'quickcab-b8b8a',
    databaseURL: 'https://quickcab-b8b8a-default-rtdb.firebaseio.com',
    storageBucket: 'quickcab-b8b8a.appspot.com',
    androidClientId: '1082266719078-o8im8a4qmnj47m8mr454i2h5jegkeskm.apps.googleusercontent.com',
    iosClientId: '1082266719078-pslorj2sjkd17fffq157o07fb2n1umro.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeHUHlfj6N8A0Aj1_ZIocE_jU2V38AXRM',
    appId: '1:1082266719078:web:cec83e55388c081bc76ea7',
    messagingSenderId: '1082266719078',
    projectId: 'quickcab-b8b8a',
    authDomain: 'quickcab-b8b8a.firebaseapp.com',
    databaseURL: 'https://quickcab-b8b8a-default-rtdb.firebaseio.com',
    storageBucket: 'quickcab-b8b8a.appspot.com',
    measurementId: 'G-Q87YMJTYMT',
  );

}